Mcc/Mcc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path,include, re_path
from cric.views import login_view, logout_view, register_view
from django.conf.urls import url
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/login/$', login_view, name='login'),
    re_path(r'^accounts/logout/$', logout_view, name='logout'),
    # path('login/', login_view, name='login'),
    # path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    path('', include('cric.urls')),

]

Mcc/cric/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

from django.conf import settings
from django.views.static import serve

app_name = 'cric'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),

    url(r'^register/success/$', views.register_success, name='success'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^password/success/$', views.password_success, name='password_success'),

    path('team_list', views.team_list, name='team_list'),

    #path('match_list', views.match_list, name='match_list'),
    path('match_list/<int:pk>', views.match_list, name='match_list'),
    path('match/<int:pk>/', views.match_detail, name='match_detail'),
    path('match/<int:pk>/edit', views.match_edit, name='match_edit'),
    path('match/new', views.match_new, name='match_new'),

    path('team/<int:pk>/edit/', views.team_edit, name='team_edit'),
    path('team/new/', views.team_new, name='team_new'),
    path('team/<int:pk>/delete/', views.team_delete, name='team_delete'),
    path('team/<int:pk>/', views.team_detail, name='team_detail'),

    path('player_list', views.player_list, name='player_list'),
    path('player_list/<int:pk>/', views.myteamplayer_list, name='myteamplayer_list'),
    path('player/new/', views.player_new, name='player_new'),
    path('player/<int:pk>/', views.player_detail, name='player_detail'),
    path('player/<int:pk>/edit/', views.player_edit, name='player_edit'),
    path('player/<int:pk>/delete/', views.player_delete, name='player_delete'),

    path('assign_role', views.assign_role, name='assign_role'),
    path('roles', views.role_list, name='role_list'),
    path('roles/delete/<int:pk>/', views.delete_role, name='delete_role'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT,})
    ]

Mcc/cric/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect

now = timezone.now()

# Homepage Views
#################
def home(request):
    matches_sch = Match.objects.filter(match_status='scheduled')
    matches_full = Match.objects.filter(match_status='finished')
    matches_live = Match.objects.filter(match_status='in_progress')
    team_live = Team.objects.filter(id=1)
    return render(request, 'base/home.html', {'matches_sch': matches_sch,
                                              'matches_full': matches_full,
                                              'matches_live': matches_live,
                                              'team_logo_live': team_live})

# Match Views
#############
def match_list(request, pk):
    if(pk == 1):
        match_list = Match.objects.filter(created_date__lte=timezone.now()).order_by('match_day', 'match_start_time')
        list_type = 'all'
    elif(pk == 2):
        match_list = Match.objects.filter(match_status='in_progress').order_by('match_day', 'match_start_time')
        list_type = 'in_progress'
    elif(pk == 3):
        match_list = Match.objects.filter(match_status='finished').order_by('match_day', 'match_start_time')
        list_type = 'finished'
    elif(pk == 4):
        match_list = Match.objects.filter(match_status='scheduled').order_by('match_day', 'match_start_time')
        list_type = 'scheduled'
    else:
        match_list = Match.objects.filter(created_date__lte=timezone.now()).order_by('match_day', 'match_start_time')
        list_type = 'all'
    return render(request, 'custom/match_list.html', {'match_list': match_list,
                                                          'list_type': list_type})

def match_detail(request, pk):
    #Getting details
    match = get_object_or_404(Match, pk=pk)
    home_team = match.home_team
    guest_team = match.guest_team
    home_score = Score.objects.filter(match=match, team=home_team)
    guest_score = Score.objects.filter(match=match, team=guest_team)

    #Getting page forms
    home_score_form = ScoreForm(team_id=home_team.id)
    guest_score_form = ScoreForm(team_id=guest_team.id)

    match_status_form = MatchStatusForm()
    match_status_form.fields['match_status'].initial = match.match_status
    match_status_form.fields['referee_comments'].initial = match.referee_comments

    #Handling POST requests
    if request.method == "POST" and 'home_score_submit' in request.POST:
        home_score_form = ScoreForm(request.POST, team_id=home_team.id)
        if home_score_form.is_valid():
            score = home_score_form.save(commit=False)
            score.created_date = timezone.now()
            score.match = get_object_or_404(Match, pk=pk)
            score.team = home_team
            score.save()
    elif request.method == "POST" and 'guest_score_submit' in request.POST:
        guest_score_form = ScoreForm(request.POST, team_id=guest_team.id)
        if guest_score_form.is_valid():
            score = guest_score_form.save(commit=False)
            score.created_date = timezone.now()
            score.match = get_object_or_404(Match, pk=pk)
            score.team = guest_team
            score.save()

    elif request.method == "POST" and 'update_match_status' in request.POST:
        match_status_form = MatchStatusForm(request.POST, instance=match)
        if match_status_form.is_valid():
            print('>>>>Match Status Valid')
            match = match_status_form.save(commit=False)
            match.home_team_score = home_score.count()
            match.guest_team_score = guest_score.count()
            print('>>Home Score - ', home_score.count())
            print('>>Guest Score - ', guest_score.count())
            match.save()

    return render(request, 'custom/match_detail.html', {'match': match,
                                                'home_team': home_team,
                                                'guest_team': guest_team,
                                                'home_score': home_score,
                                                'guest_score': guest_score,
                                                'match_status_form': match_status_form,
                                                'home_score_form': home_score_form,
                                                'guest_score_form': guest_score_form})

@login_required
def match_edit(request, pk):
    match = get_object_or_404(Match, pk=pk)
    if request.method == "POST":
        #update
        form = MatchForm(request.POST,instance=match)
        if form.is_valid():
            match = form.save(commit=False)
            match.updated_date = timezone.now()
            match.save()
            match_list = Match.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/match_list.html', {'match_list': match_list,
                                                              'list_type': 'all'})
    else:
        # edit
        form = MatchForm(instance = match)
    return render(request, 'custom/match_edit.html', {'form': form})

@login_required
def match_new(request):
    if request.method == "POST":
        #update
        form = MatchForm(request.POST)
        if form.is_valid():
            match = form.save(commit=False)
            match.created_date = timezone.now()
            match.save()
            match_list = Match.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/match_list.html', {'match_list': match_list,
                                                              'list_type': 'all'})
    else:
        # edit
        form = MatchForm()
    return render(request, 'custom/match_edit.html', {'form': form})


# Team Views
#############
@login_required
def team_edit(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method == "POST":
        #update
        form = TeamForm(request.POST,instance=team)
        if form.is_valid():
            team = form.save(commit=False)
            team.updated_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/team_list.html', {'team_list': teams})
    else:
        # edit
        form = TeamForm(instance = team)
    return render(request, 'custom/team_edit.html', {'form': form})

@login_required
def team_new(request):
    if request.method == "POST":
        #update
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/team_list.html', {'team_list': teams})
    else:
        # edit
        form = TeamForm()
    return render(request, 'custom/team_edit.html', {'form': form})

def team_list(request):
    team_list = Team.objects.filter(created_date__lte=timezone.now())
    return render(request, 'custom/team_list.html',
                 {'team_list': team_list})

def team_detail(request, pk):
  cap='None';
  Won=0;
  Lost=0;
  Drawn=0;
  playerscore_count=0;
  playerscore=[]
  try:
    team = get_object_or_404(Team, pk=pk)
    name=team.team_name
    score_list = Score.objects.filter(team=team).order_by('-created_date')[:10]
    matchesasguest=Match.objects.filter(guest_team=team.id)
    for match in matchesasguest:
     if match.guest_team_score > match.home_team_score:
      Won=Won+1;
     if match.guest_team_score == match.home_team_score:
      Drawn=Drawn+1
     if  match.guest_team_score < match.home_team_score:
      Lost=Lost+1

    matchesashome = Match.objects.filter(home_team=team.id)
    for match in matchesashome:
     if match.home_team_score > match.guest_team_score:
      Won = Won + 1;
     if match.guest_team_score == match.home_team_score:
      Drawn = Drawn + 1
     if match.home_team_score < match.guest_team_score:
      Lost = Lost + 1
    players = Player.objects.filter(team=team.id).filter(eligibility_status='eligible')
    for player in players:
     #playergoal=Goal.objects.filter(player=player)
     if player.team_role == 'captain':
         cap = player.first_name +" "+ player.last_name
     #playergoal_count=playergoal.count()
    score_count = score_list.count()
    return render(request, 'custom/team_detail.html', {'team': team,
                                                'score_list': score_list,
                                                'score_count': score_count,'players':players,'playerscore_count':playerscore_count,
                                                'cap':cap,'Won':Won,'Lost':Lost,'Drawn':Drawn
                                                      })
  except Team.DoesNotExist:
      return render(request, 'custom/myteam_detail.html',
                    {'goal_list': None,'cap':None,'players':None,'score_count':0,'playerscore_count':0})

@login_required
def team_delete(request, pk):
    team = get_object_or_404(Team, pk=pk)
    team.delete()
    return redirect('cric:team_list')


# Player Views
##############
def player_list(request):
    player_list = Player.objects.filter(created_date__lte=timezone.now())
    player_count = player_list.count()
    return render(request, 'custom/player_list.html',
                 {'player_list': player_list,
                  'player_count': player_count})

def player_detail(request, pk):
    player = get_object_or_404(Player, pk=pk)
    team = player.team

Mcc/cric/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MCC</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
<!--Navigation Bar-->
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'cric:home' %}"><img width="80px" src="{% static 'images/logo.png' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            {% with url_name=request.resolver_match.url_name %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'cric:home' %}">Home</a>
                </li>
                <li class="nav-item {% if url_name == 'match_list' %}active{% endif %}">
{#                    <a class="nav-link" href="{% url 'cric:match_list' %}">Matches</a>#}
                    <a class="nav-link" href="{% url 'cric:match_list' pk=1%}">Matches</a>
                </li>
                <li class="nav-item {% if url_name == 'team_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'cric:team_list' %}">Teams</a>
                </li>
                <li class="nav-item {% if url_name == 'player_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'cric:player_list' %}">Players</a>
                </li>
                 {% if request.user.is_superuser or user.groups.all and user.groups.all.0.name == "Admin" %}
                 <li class="nav-item {% if url_name == 'role_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'cric:role_list' %}">Roles</a>
                </li>
                {% endif %}
                {% if user.is_authenticated and user.groups.all and user.groups.all.0.name == "Coach" %}
                <li class="nav-item {% if url_name == 'myteamplayer_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'cric:myteamplayer_list' pk=user.pk %}" >My Team</a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.first_name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                             <a class="dropdown-item" href="{% url 'cric:change_password' %}">Change Password</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

Mcc/cric/templates/base/base_register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MCC</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
<!--Navigation Bar-->
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'cric:home' %}"><img width="200px" src="{% static 'images/logo.png' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.first_name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                             <a class="dropdown-item" href="{% url 'cric:change_password' %}">Change Password</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<br/>
<div style="margin-left:10%" align=center>
<div class='col-sm-8 col-sm-offset-3'>

              {% block body %}
              {% endblock %}
        </div>
</div>



  </body>
</html>

Mcc/cric/templates/base/home.html
{% extends 'base/base.html' %}

{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <h3>LIVE</h3>

              <div class="row text-center">
                <div class=" col-12 col-sm-12 col-md-12 col-lg-6">
                    <table width="850px" border="1px"><tr>
                  {% for matcheslive in matches_live %}
                        <td width="80px" padding="5px">

                        <div>
                            <b> {{matcheslive.field}} | Started at {{matcheslive.match_start_time}}</b>
                            <hr>
                        </div>


                        <div class="row">
                            <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                                <img src="{{ matcheslive.home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="70"><br/>
                                <b>{{matcheslive.home_team}}</b>
                            </div>
                            <div class="col-4 col-sm-4 col-md-4 col-lg-4 my-auto">
                                <span class="mcc-livescore">
                                    {{matcheslive.home_team_score}} - {{matcheslive.guest_team_score}}
                                </span>
                                <p class="mcc-livescore-sub">

                                    In Progress
                                </p>
                            </div>
                       <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                           <img src="{{ matcheslive.guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="70"> <br/>
                        <b>{{ matcheslive.guest_team}}</b>
                    </div>
                    </div>
                            </td>
                    {% endfor %}
                </tr></table>
              </div>
            </div>

</div>


<table width="1250px" cellpadding="10px"cellspacing="10px">
    <tr>
        <td width="650px" border="2px">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Upcoming Matches</legend>
                <div class="control-group">
                   <div class="table-responsive">
                        <table width="450px" cellpadding="10px"cellspacing="10px">
                            <tbody>
                                {% for match in matches_sch %}
                                <tr style="border-bottom: 1px solid red">
                                    <div class="card bg-light">

                                            <td style="text-align: right"><img src="{{ match.home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="70"> <br/>
                                              <b>{{ match.home_team}}</b></td>
                                            <td style="text-align: center"><strong>vs</strong></td>
                                            <td><img src="{{ match.guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="70"> <br/>
                                              <b>{{ match.guest_team}}</b></td>
                                            <td> at - {{ match.match_day }} </td>
                                        <td><td> <b>{{match.referee_comments}}</b></td></td>
                                    </div>
                                </tr>

                                {% endfor %}
                            </tbody>
                      </table>
                </div>
                </div>
            </fieldset>
        </td>
        <td>
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Results</legend>
                <div class="control-group">
                   <div class="table-responsive">
                        <table width="450px" cellpadding="10px"cellspacing="10px">
                            <tbody>
                                {% for matchesfull in matches_full %}
                                <tr style="border-bottom: 1px solid red">
                                    <div class="card bg-light">

                                            <td style="text-align: right"><img src="{{ matchesfull.home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="70"> <br/>
                                              <b>{{ matchesfull.home_team}}</b></td>
                                            <td style="text-align: center"><strong>vs</strong></td>
                                            <td><img src="{{ matchesfull.guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="70"> <br/>
                                              <b>{{ matchesfull.guest_team}}</b></td>
                                            <td> day - {{ matchesfull.match_day }} </td>
                                        <td><td> <b>{{matchesfull.referee_comments}}</b></td></td>

                                    </div>
                                </tr>

                                {% endfor %}
                            </tbody>
                      </table>
                </div>
                </div>
            </fieldset>
        </td>
    </tr>
</table>


{% endblock %}

Mcc/cric/templates/base/match_list_base.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
    <div class="nav-scroller bg-white shadow-sm">
        <nav class="nav nav-underline">
        {% with url_name=request.resolver_match.url_name %}
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'all' %}active{% endif %}" href="{% url 'cric:match_list' pk=1%}">All Matches</a>
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'in_progress' %}active{% endif %}" href="{% url 'cric:match_list' pk=2%}">Live</a>
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'finished' %}active{% endif %}" href="{% url 'cric:match_list' pk=3%}">Results</a>
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'scheduled' %}active{% endif %}" href="{% url 'cric:match_list' pk=4%}">Upcoming</a>
            <a class="btn btn-info" href="{% url 'cric:match_new' %}" data-toggle="tooltip" title="Add a Match">
                <i class="fas fa-plus" style="font-size: 1.2em; margin: 0rem; color: #FFFFFF; text-decoration: none;"></i>
            </a>
        {% endwith %}
        </nav>
    </div>
    {% block match_list_content %}
    {% endblock %}
{% endblock%}