Mcc/Mcc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path,include, re_path
from cric.views import login_view, logout_view, register_view
from django.conf.urls import url
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/login/$', login_view, name='login'),
    re_path(r'^accounts/logout/$', logout_view, name='logout'),
    # path('login/', login_view, name='login'),
    # path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    path('', include('cric.urls')),

]

Mcc/cric/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

from django.conf import settings
from django.views.static import serve

app_name = 'cric'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),

    url(r'^register/success/$', views.register_success, name='success'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^password/success/$', views.password_success, name='password_success'),

    path('team_list', views.team_list, name='team_list'),

    #path('match_list', views.match_list, name='match_list'),
    path('match_list/<int:pk>', views.match_list, name='match_list'),
    path('match/<int:pk>/', views.match_detail, name='match_detail'),
    path('match/<int:pk>/edit', views.match_edit, name='match_edit'),
    path('match/new', views.match_new, name='match_new'),

    path('team/<int:pk>/edit/', views.team_edit, name='team_edit'),
    path('team/new/', views.team_new, name='team_new'),
    path('team/<int:pk>/delete/', views.team_delete, name='team_delete'),
    path('team/<int:pk>/', views.team_detail, name='team_detail'),

    path('player_list', views.player_list, name='player_list'),
    path('player_list/<int:pk>/', views.myteamplayer_list, name='myteamplayer_list'),
    path('player/new/', views.player_new, name='player_new'),
    path('player/<int:pk>/', views.player_detail, name='player_detail'),
    path('player/<int:pk>/edit/', views.player_edit, name='player_edit'),
    path('player/<int:pk>/delete/', views.player_delete, name='player_delete'),

    path('assign_role', views.assign_role, name='assign_role'),
    path('roles', views.role_list, name='role_list'),
    path('roles/delete/<int:pk>/', views.delete_role, name='delete_role'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT,})
    ]

Mcc/cric/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect

now = timezone.now()

# Homepage Views
#################
def home(request):
    matches_sch = Match.objects.filter(match_status='scheduled')
    matches_full = Match.objects.filter(match_status='finished')
    matches_live = Match.objects.filter(match_status='in_progress')
    team_live = Team.objects.filter(id=1)
    return render(request, 'base/home.html', {'matches_sch': matches_sch,
                                              'matches_full': matches_full,
                                              'matches_live': matches_live,
                                              'team_logo_live': team_live})

# Match Views
#############
def match_list(request, pk):
    if(pk == 1):
        match_list = Match.objects.filter(created_date__lte=timezone.now()).order_by('match_day', 'match_start_time')
        list_type = 'all'
    elif(pk == 2):
        match_list = Match.objects.filter(match_status='in_progress').order_by('match_day', 'match_start_time')
        list_type = 'in_progress'
    elif(pk == 3):
        match_list = Match.objects.filter(match_status='finished').order_by('match_day', 'match_start_time')
        list_type = 'finished'
    elif(pk == 4):
        match_list = Match.objects.filter(match_status='scheduled').order_by('match_day', 'match_start_time')
        list_type = 'scheduled'
    else:
        match_list = Match.objects.filter(created_date__lte=timezone.now()).order_by('match_day', 'match_start_time')
        list_type = 'all'
    return render(request, 'custom/match_list.html', {'match_list': match_list,
                                                          'list_type': list_type})

def match_detail(request, pk):
    #Getting details
    match = get_object_or_404(Match, pk=pk)
    home_team = match.home_team
    guest_team = match.guest_team
    home_score = Score.objects.filter(match=match, team=home_team)
    guest_score = Score.objects.filter(match=match, team=guest_team)

    #Getting page forms
    home_score_form = ScoreForm(team_id=home_team.id)
    guest_score_form = ScoreForm(team_id=guest_team.id)

    match_status_form = MatchStatusForm()
    match_status_form.fields['match_status'].initial = match.match_status
    match_status_form.fields['referee_comments'].initial = match.referee_comments

    #Handling POST requests
    if request.method == "POST" and 'home_score_submit' in request.POST:
        home_score_form = ScoreForm(request.POST, team_id=home_team.id)
        if home_score_form.is_valid():
            score = home_score_form.save(commit=False)
            score.created_date = timezone.now()
            score.match = get_object_or_404(Match, pk=pk)
            score.team = home_team
            score.save()
    elif request.method == "POST" and 'guest_score_submit' in request.POST:
        guest_score_form = ScoreForm(request.POST, team_id=guest_team.id)
        if guest_score_form.is_valid():
            score = guest_score_form.save(commit=False)
            score.created_date = timezone.now()
            score.match = get_object_or_404(Match, pk=pk)
            score.team = guest_team
            score.save()

    elif request.method == "POST" and 'update_match_status' in request.POST:
        match_status_form = MatchStatusForm(request.POST, instance=match)
        if match_status_form.is_valid():
            print('>>>>Match Status Valid')
            match = match_status_form.save(commit=False)
            match.home_team_score = home_score.count()
            match.guest_team_score = guest_score.count()
            print('>>Home Score - ', home_score.count())
            print('>>Guest Score - ', guest_score.count())
            match.save()

    return render(request, 'custom/match_detail.html', {'match': match,
                                                'home_team': home_team,
                                                'guest_team': guest_team,
                                                'home_score': home_score,
                                                'guest_score': guest_score,
                                                'match_status_form': match_status_form,
                                                'home_score_form': home_score_form,
                                                'guest_score_form': guest_score_form})

@login_required
def match_edit(request, pk):
    match = get_object_or_404(Match, pk=pk)
    if request.method == "POST":
        #update
        form = MatchForm(request.POST,instance=match)
        if form.is_valid():
            match = form.save(commit=False)
            match.updated_date = timezone.now()
            match.save()
            match_list = Match.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/match_list.html', {'match_list': match_list,
                                                              'list_type': 'all'})
    else:
        # edit
        form = MatchForm(instance = match)
    return render(request, 'custom/match_edit.html', {'form': form})

@login_required
def match_new(request):
    if request.method == "POST":
        #update
        form = MatchForm(request.POST)
        if form.is_valid():
            match = form.save(commit=False)
            match.created_date = timezone.now()
            match.save()
            match_list = Match.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/match_list.html', {'match_list': match_list,
                                                              'list_type': 'all'})
    else:
        # edit
        form = MatchForm()
    return render(request, 'custom/match_edit.html', {'form': form})


# Team Views
#############
@login_required
def team_edit(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method == "POST":
        #update
        form = TeamForm(request.POST,instance=team)
        if form.is_valid():
            team = form.save(commit=False)
            team.updated_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/team_list.html', {'team_list': teams})
    else:
        # edit
        form = TeamForm(instance = team)
    return render(request, 'custom/team_edit.html', {'form': form})

@login_required
def team_new(request):
    if request.method == "POST":
        #update
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'custom/team_list.html', {'team_list': teams})
    else:
        # edit
        form = TeamForm()
    return render(request, 'custom/team_edit.html', {'form': form})

def team_list(request):
    team_list = Team.objects.filter(created_date__lte=timezone.now())
    return render(request, 'custom/team_list.html',
                 {'team_list': team_list})

def team_detail(request, pk):
  cap='None';
  Won=0;
  Lost=0;
  Drawn=0;
  playerscore_count=0;
  playerscore=[]
  try:
    team = get_object_or_404(Team, pk=pk)
    name=team.team_name
    score_list = Score.objects.filter(team=team).order_by('-created_date')[:10]
    matchesasguest=Match.objects.filter(guest_team=team.id)
    for match in matchesasguest:
     if match.guest_team_score > match.home_team_score:
      Won=Won+1;
     if match.guest_team_score == match.home_team_score:
      Drawn=Drawn+1
     if  match.guest_team_score < match.home_team_score:
      Lost=Lost+1

    matchesashome = Match.objects.filter(home_team=team.id)
    for match in matchesashome:
     if match.home_team_score > match.guest_team_score:
      Won = Won + 1;
     if match.guest_team_score == match.home_team_score:
      Drawn = Drawn + 1
     if match.home_team_score < match.guest_team_score:
      Lost = Lost + 1
    players = Player.objects.filter(team=team.id).filter(eligibility_status='eligible')
    for player in players:
     #playergoal=Goal.objects.filter(player=player)
     if player.team_role == 'captain':
         cap = player.first_name +" "+ player.last_name
     #playergoal_count=playergoal.count()
    score_count = score_list.count()
    return render(request, 'custom/team_detail.html', {'team': team,
                                                'score_list': score_list,
                                                'score_count': score_count,'players':players,'playerscore_count':playerscore_count,
                                                'cap':cap,'Won':Won,'Lost':Lost,'Drawn':Drawn
                                                      })
  except Team.DoesNotExist:
      return render(request, 'custom/myteam_detail.html',
                    {'goal_list': None,'cap':None,'players':None,'score_count':0,'playerscore_count':0})

@login_required
def team_delete(request, pk):
    team = get_object_or_404(Team, pk=pk)
    team.delete()
    return redirect('cric:team_list')


# Player Views
##############
def player_list(request):
    player_list = Player.objects.filter(created_date__lte=timezone.now())
    player_count = player_list.count()
    return render(request, 'custom/player_list.html',
                 {'player_list': player_list,
                  'player_count': player_count})

def player_detail(request, pk):
    player = get_object_or_404(Player, pk=pk)
    team = player.team

Mcc/cric/templates/custom/assign_roles.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-6">
    <h1>Assign Roles</h1>
     <div style="width:30%">
    <form method="POST">{%csrf_token%}
           {% for field in form %}
                <div class="row">
                     <div class="col-sm-8">
                         {{ field.label_tag }}
                     </div>
                     <div class="col-sm-3">
                         {{ field }}
                     </div>
                </div>
           {% endfor %}
     <div class="row">
         <div class="col-sm-3">
        <button type="submit" class="save btn btn-default">Send Invitation</button>
         </div>
     </div>
    </form>
     </div>
</div>
</div>
</div>
{% endblock %}

Mcc/cric/templates/custom/goal_edit.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-6">
    <h1>Add/Edit Goal</h1>
    <form method="POST" class="sm-form">{%csrf_token%}
        {{form|crispy}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
</div>
</div>
{% endblock %}

Mcc/cric/templates/custom/match_detail.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid padding">
<div class="row justify-content-center text-center">
    <div class="mcc-scorecard col-12 col-sm-12 col-md-10 col-lg-8">
        <div class="row text-left mt-2">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <h6>{{match.match_day}} | {{match.field}} | Started at {{match.match_start_time}}</h6>
                <hr>
            </div>
        </div>
        <div class="row mx-1">
            <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                <img src="{{ home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
                <h3>{{home_team.team_name}}</h3>
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4 my-auto">
                <span class="mcc-livescore">
                         <strong>({{match.home_team_score}} - {{match.guest_team_score}})</strong>
                    </td>
                </span>

                <p class="mcc-livescore-sub">
                {% if match.match_status == 'scheduled' %}
                    Scheduled
                {% elif match.match_status == 'in_progress'%}
                    In Progress
                {% elif match.match_status == 'finished'%}
                    Full Time
                {% elif match.match_status == 'cancelled'%}
                    Cancelled
                {% elif match.match_status == 'abandoned'%}
                    Abandoned
                {% else %}
                    Status - Not Available
                {% endif %}

                </p>

            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                <img src="{{ guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
                <h3>{{guest_team.team_name}}</h3>
            </div>
        </div>
        <div class="row mx-1">
            <div class="mcc-livescore-sub col-6 col-sm-6 col-md-6 col-lg-6 text-right">
                {% for score in home_score%}
                    <p>
                        {{score.player}}&nbsp;{{score.score_minute}}'
                        <i class="far fa-futbol"></i>
                    </p>
                {% endfor%}
            </div>
            <div class="mcc-livescore-sub col-6 col-sm-6 col-md-6 col-lg-6 text-left">
                {% for score in guest_goals%}
                    <p>
                        <i class="far fa-futbol"></i>&nbsp;
                        {{score.score_minute}}'&nbsp;{{score.player}}
                    </p>
                {% endfor%}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

Mcc/cric/templates/custom/match_edit.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-6">
    <h1>Add/Edit Match</h1>
    <form method="POST">{%csrf_token%}
        {{form|crispy}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
</div>
</div>
{% endblock %}

Mcc/cric/templates/custom/match_list.html
{% extends "base/match_list_base.html" %}
{% load static %}

{% block match_list_content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <tbody>
                {% for match in match_list %}
                <tr>
                    <td>
                        <a class="fa-icons" href="{% url 'cric:match_detail' pk=match.pk %}">
                            <i class="fa fa-eye"></i>
                        </a>
                        &nbsp
                        <a class="fa-icons" href="{% url 'cric:match_edit' pk=match.pk %}">
                            <i class="fa fa-edit"></i>
                        </a>
                        &nbsp
                        <a class="fa-icons" href="#">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td style="text-align: right">
                        <img src="{{ team.team_logo.url }}" width="20">
                        {{ match.home_team}}
                    </td>
                    <td style="text-align: center">
                        <strong>({{match.home_team_score}} - {{match.guest_team_score}})</strong>
                    </td>
                    <td>{{ match.guest_team }}</td>
                    <td>{{ match.match_day }}, {{ match.match_start_time }}</td>
                    <td>
                        {% if match.match_status == 'scheduled' %}
                            Scheduled
                        {% elif match.match_status == 'in_progress'%}
                            In Progress
                        {% elif match.match_status == 'finished'%}
                            Finished
                        {% elif match.match_status == 'cancelled'%}
                            Cancelled
                        {% elif match.match_status == 'abandoned'%}
                            Abandoned
                        {% else %}
                            Status - Not Available
                        {% endif %}
                    </td>
                    <td>{{ match.field }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
{% endblock%}

Mcc/cric/templates/custom/myteamplayer_list.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid padding">
    <div class="row padding">
        <div class="col-md-12">
          {% if myplayer %}
            <table class="table table-striped table-bordered table-hover">
                  <thead>
                 <tr class="bg-info">
                      <th>PLAYER NAME </th>
                      <th>ROLE IN TEAM</th>
                      <th>SQUAD POSITION</th>

                  </tr>
                     <div class="col-xs4- col-sm-4 col-md-2 col-lg-1">
                         <a href="{% url 'cric:player_new' %}"  class="btn btn-light">
                         <i class="fas fa-plus"></i>
                         </a>
                     </div>
                  </thead>
                  <tbody>
                  {% for player in myplayer %}
                  <tr>
                      <td>{{ player.first_name}}{{ player.last_name }}</td>
                      <td>{{ player.team_role }}</td>
                      <td>{{ player.squad_position }}</td>

                      <td><a href="{% url 'cric:player_edit' pk=player.pk %}" class="card-link">Edit</a></td>
                      <td><a href="{% url 'cric:player_delete' pk=player.pk %}" onclick="return confirm('Are you sure you want to Delete?')" class="card-link">Delete</a></td>
                  </tr>
                  {% endfor %}

                  </tbody>
              </table>
            {% else %}
            <p> No Team assigned to the coach yet, please contact Admin.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

Mcc/cric/templates/custom/player_list.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-12">
    <p>
        Total Number of Players: <strong>{{player_count}}</strong><br>
    </p>
    <p>
        <a href="{% url 'cric:player_new' %}"  class="btn btn-primary">
                <i class="fas fa-plus" style="font-size: 1.2em; margin: 0rem; color: #FFFFFF; text-decoration: none;"></i> Add More</a>
    </p>
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th>Actions</th>
                    <th>Full Name</th>
                    <th>Team</th>
                    <th>Squad Position</th>
                </tr>
            </thead>
            <tbody>
                {% for player in player_list %}
                <tr>
                    <td>
                        <a class="fa-icons" href="{% url 'cric:player_detail' pk=player.pk %}">
                            <i class="fa fa-eye"></i>
                        </a>
                        &nbsp
                        <a class="fa-icons" href="{% url 'cric:player_edit' pk=player.pk %}">
                            <i class="fa fa-edit"></i>
                        </a>
                        &nbsp
                        <a class="fa-icons" href="{% url 'cric:player_delete' pk=player.pk %}" onclick="return confirm('Are you sure you want to Delete?')">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td>
                        {{ player.first_name}}&nbsp{{player.last_name}}
                    </td>
                    <td>{{ player.team }}</td>
                    <td>{{ player.squad_position }}</td>
                </tr>
                {% endfor %}
            </tbody>
      </table>
    </div>
</div>
</div>
</div>
{% endblock%}

Mcc/cric/templates/custom/roles.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-12">
    <div class="tabbable">
          <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                      <a class="nav-link active" id="roleslist-tab" data-toggle="tab" href="#roleslist" role="tab" aria-controls="roleslist" aria-selected="true">Roles</a>
                  </li>
                   <li>
                     <a class="nav-link" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="true">Pending</a>
                 </li>

          </ul></br>
            {% if sent == "True" %}
                <div class="page-container">
                    <p>Email has been successfully sent to {{ emailid }}</p>
                </div>
            {% endif %}
          <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active col-md-8" role="tabpanel" aria-labelledby="roleslist-tab" id="roleslist">
                <p>
        <a href="{% url 'cric:assign_role' %}"  class="btn btn-primary">
                <i class="fas fa-plus" style="font-size: 1.2em; margin: 0rem; color: #FFFFFF; text-decoration: none;"></i> Add Roles</a>
    </p>
                  <table class="table table-striped table-bordered table-hover">
                     <thead>
                         <tr class="bg-info">
                             <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                         </tr>
                     </thead>
                      <tbody>
                        {% for user in user_list %}
                            <tr>
                                <td>{{ user.username }} </td>
                                <td>{{ user.email }}</td>
                                {% if user.groups.all.0 %}
                                     <td>{{ user.groups.all.0 }}</td>
                                {% else %}
                                    <td>Super User</td>
                                {% endif %}
                            </tr>
                        {% endfor %}

                        </tbody>
                      </table>
               </div>
              <div class="tab-pane fade col-md-8" id="pending" role="tabpanel" aria-labelledby="pending-tab" >
                  <table class="table table-striped table-bordered table-hover">
                      <thead>
                         <tr class="bg-info">
                             <th>Role</th>
                            <th>Receiver Name</th>
                            <th>Receiver Email</th>
                             <th>Registered</th>
                             <th>Action</th>
                         </tr>
                     </thead>
                      <tbody>
                        {% for role in roles_list %}
                            <tr>
                                <td>{{ role.role }} </td>
                                <td>{{ role.receiver_name }}</td>
                                <td>{{ role.receiver_email }}</td>
                                <td>{{ role.registered }}</td>
                                <td><a href="{% url 'cric:delete_role' pk=role.pk %}"
                                   onclick="return confirm('Are you sure you want to delete?')"
                                   class="btn btn-danger">Delete</a>
                            </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                      </table>
              </div>

          </div>
    </div>
</div>
</div>
</div>
{% endblock%}

Mcc/cric/templates/custom/roles_list.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="container padding">
<div class="row padding">
<table class="table table-striped table-bordered table-hover">
<thead>

 <tr class="bg-info">
     <th>Name</th>
    <th>Email</th>
    <th>Role</th>
 </tr>
</thead>
<tbody>
{% for role in role_list %}
    <tr>
        <td>{{ role.username }} </td>
        <td>{{ role.email }}</td>
        <td>{{ role.groups.all.0 }}</td>
    </tr>
{% endfor %}

</tbody>
</table>

</div>
 <a href="{% url 'cric:assign_role' %}" >
            <span class="btn btn-primary">Assign New Role</span></a>
</div>

{% endblock %}

Mcc/cric/templates/custom/team_detail.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
    <div class="col-12 col-sm-12 col-md-2">
        <img src="{{ team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
    </div>
    <div class="col-12 col-sm-12 col-md-6">
        <h1>{{team.team_name}}</h1>
        <hr>
        <p>
            <small class="text-muted">School</small><br>
            {{team.school}}
        </p>
        <p>
            <small class="text-muted">Coach</small><br>
            {{team.coach}}
        </p>
        <p>
            <small class="text-muted">Captain</small><br>
             {{ cap }}
        </p>
        <p>
            <small class="text-muted">Summary About Team</small><br>
            {{score_count}}
        </p>
    </div>
</div>
<div class="row padding">
    <div class="col-12 col-sm-12 col-md-8">
        <h3>Matches </h3>
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th>Won</th>
                    <th>Lost</th>
                    <th>Drawn</th>
                </tr>
            </thead>
            <tbody>

                    <tr>
                        <td>{{Won}}</td>
                        <td>{{Lost}}</td>
                        <td>{{ Drawn }}</td>
                    </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row padding">
    <div class="col-12 col-sm-12 col-md-8">
        <h3>Team Players</h3>
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th>Player</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for player in players %}
                    {{ sort }}
                    <tr>
                       <td><a href="{% url 'cric:player_detail' pk=player.pk %}">{{player.first_name}}{{ player.last_name }}</a> </td>
                        <td>{{player.eligibility_status}}</td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
{% endblock %}

Mcc/cric/templates/custom/team_list.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="container padding">
<div class="row padding">
{% for team in team_list %}
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
    <div class="card bg-light">
        <img src="{{ team.team_logo_url }}" class="mx-auto mt-5" width="125">
        <div class="card-body text-center">
            <h3 class="card-title">{{team.team_name}}</h3>
            <p class="card-text">
                {{team.school}}<br>
                Coach - {{team.coach}}
            </p>
            <a href="{% url 'cric:team_detail' pk=team.pk %}" class="card-link">View</a>
            <a href="{% url 'cric:team_edit' pk=team.pk %}" class="card-link">Edit</a>
            <a href="{% url 'cric:team_delete' pk=team.pk %}" onclick="return confirm('Are you sure you want to Delete?')" class="card-link">Delete</a>
        </div>
    </div>
</div>
{% endfor %}
<p>
        <a href="{% url 'cric:team_new' %}"  class="btn btn-primary">
                <i class="fas fa-plus" style="font-size: 1.2em; margin: 0rem; color: #FFFFFF; text-decoration: none;"></i> Add Team</a>
    </p>
<!--<div class="col-md-12">-->
<!--<a href="{% url 'cric:team_new' %}" class="btn btn-primary" class="topright">Add Team</a>-->

</div>
<hr class="my-4">
</div>
{% endblock %}